"""Build the minimal demo, loading all values from outputs/final_results.json."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

HTML = r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Development Evidence Demo</title><style>body{font-family:Arial,"Microsoft YaHei",sans-serif;max-width:1000px;margin:30px auto;padding:0 18px;color:#173b35;background:#fffdf7}.banner{padding:14px;background:#fff1df;border:1px solid #e0a36a;margin-bottom:20px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.card{background:white;border:1px solid #ddd4c6;padding:14px}.wide{margin-top:16px;background:white;border:1px solid #ddd4c6;padding:16px}.value{font-size:24px;font-weight:700}.muted{color:#6b7280;font-size:13px}table{width:100%;border-collapse:collapse}td,th{padding:7px;border-bottom:1px solid #e7e0d6;text-align:left}@media(max-width:700px){.grid{grid-template-columns:1fr 1fr}}</style><body><div id="app">Loading…</div><script>
const fmt=(x,d=4)=>x==null?'NO_EFFECTIVE_EVIDENCE':Number(x).toFixed(d);const esc=x=>String(x??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
fetch('../../outputs/final_results.json').then(r=>r.json()).then(a=>{const d=a.development_results,r=d.raw_summary,x=d.adjusted_summary, rec=d.explain_records, s=a.sensitivity.rows, t=a.transfer_validation; const shown=rec.find(v=>v.evaluation_status!=='NO_EFFECTIVE_EVIDENCE')||rec[0]; document.getElementById('app').innerHTML=`<div class="banner"><b>DEVELOPMENT_ONLY · NOT_HUMAN_VALIDATED</b><br>Human Gate 未完成；formal_gate_eligible=false。事实源：outputs/final_results.json</div><h1>Input → Raw → Reliability → Adjusted → Explain → Evaluation Status → What-if</h1><div class="grid"><div class="card"><div class="muted">Input records</div><div class="value">${a.data_identity.sample_count}</div></div><div class="card"><div class="muted">Raw ABL</div><div class="value">${fmt(r.ABL)}</div></div><div class="card"><div class="muted">Reliability weight</div><div class="value">${fmt(x.effective_weight,2)}</div></div><div class="card"><div class="muted">Adjusted ABL</div><div class="value">${fmt(x.ABL)}</div></div></div><div class="wide"><h2>Explain</h2><p><b>${esc(shown.record_id)}</b> · status <b>${esc(shown.evaluation_status)}</b></p><p>${esc(shown.explanation)}</p><p class="muted">positive: ${esc(shown.positive_factors.join(', ')||'none')}<br>negative: ${esc(shown.negative_factors.join(', ')||'none')}</p></div><div class="wide"><h2>Evaluation Status distribution</h2><p>${['DEVELOPMENT_ONLY_STRUCTURAL_SUPPORT','LOW_SUPPORT','NO_EFFECTIVE_EVIDENCE'].map(k=>k+': '+rec.filter(v=>v.evaluation_status===k).length).join(' · ')}</p></div><div class="wide"><h2>What-if</h2><table><thead><tr><th>parameter</th><th>change</th><th>Δ reliability</th><th>Δ adjusted score</th><th>status changed</th></tr></thead><tbody>${s.map(v=>`<tr><td>${v.parameter}</td><td>${v.change}</td><td>${Number(v.delta_reliability).toFixed(5)}</td><td>${v.delta_adjusted_score==null?'—':Number(v.delta_adjusted_score).toFixed(5)}</td><td>${v.evaluation_status_changed}</td></tr>`).join('')}</tbody></table></div><div class="wide"><h2>Transfer validation</h2><p>structural transfer: ${t.structural_transfer}; reliability separation: ${t.reliability_separation}; development-stage structural stability: ${t.sensitivity_robustness}; risk–coverage: ${t.risk_coverage_improvement}; trading advantage: ${t.trading_advantage}.</p></div>`}).catch(e=>document.getElementById('app').textContent='无法读取统一 artifact: '+e);</script></body></html>'''

if __name__ == '__main__':
    (ROOT / 'reports/demo/index.html').write_text(HTML, encoding='utf-8')
    print('demo=written')
